/* Pure plan geometry. All model distances are metres. */
(function(root){
'use strict';
const R=6378137, DEG=Math.PI/180, MAX_ITEMS=12000;
const PRODUCTS={lion:{name:'Lion Panel',l:2.41,w:3,colour:'#f7cf20'},hybrid:{name:'Hybrid Panel',l:2.44,w:3,colour:'#e5a32c'},tuff:{name:'TuffTrak',l:2.5,w:3,colour:'#5eb6df'},sabre:{name:'Sabre-X',l:1.8,w:3.8,colour:'#c2cad0'}};
const ACCESSORIES={ramp:{name:'Ramp',l:.25,w:3,colour:'#3ac7cd'},pvc:{name:'PVC',l:.5,w:3,colour:'#9675d9'},alL:{name:'Aluminium diversion · left 9°',l:.75,w:3,wedge:9,dir:-1,colour:'#ef8739'},alR:{name:'Aluminium diversion · right 9°',l:.75,w:3,wedge:9,dir:1,colour:'#ef8739'},sdL:{name:'Sabre-X diversion · left 15°',l:1,w:3.8,wedge:15,dir:-1,colour:'#e771ad'},sdR:{name:'Sabre-X diversion · right 15°',l:1,w:3.8,wedge:15,dir:1,colour:'#e771ad'},sr:{name:'Sabre-X ramp',l:.25,w:1.8,colour:'#79b967'}};
const id=()=>globalThis.crypto?.randomUUID?.()||'q'+Date.now().toString(36)+Math.random().toString(36).slice(2);
const distance=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
function project(ll){const lat=Math.max(-85,Math.min(85,ll.lat));return{x:R*ll.lng*DEG,y:R*Math.log(Math.tan(Math.PI/4+lat*DEG/2))}}
function unproject(p){return{lat:(2*Math.atan(Math.exp(p.y/R))-Math.PI/2)/DEG,lng:p.x/R/DEG}}
function toLocal(ll,origin){const a=project(origin),b=project(ll),s=Math.cos(origin.lat*DEG);return{x:(b.x-a.x)*s,y:(a.y-b.y)*s}}
function toLatLng(p,origin){const a=project(origin),s=Math.cos(origin.lat*DEG);return unproject({x:a.x+p.x/s,y:a.y-p.y/s})}
function rotate(p,a,o={x:0,y:0}){const x=p.x-o.x,y=p.y-o.y;return{x:o.x+x*Math.cos(a)-y*Math.sin(a),y:o.y+x*Math.sin(a)+y*Math.cos(a)}}
function local(p,q){return rotate({x:p.x-q.x,y:p.y-q.y},-q.a)}
function corners(q){const L=q.l/2,W=q.w/2;let c=[{x:-L,y:-W},{x:L,y:-W},{x:L,y:W},{x:-L,y:W}];if(q.wedge){const t=Math.tan(q.wedge*DEG)*q.w/2;if(q.dir>0){c[0].x+=t;c[3].x-=t}else{c[1].x-=t;c[2].x+=t}}return c.map(p=>{p=rotate(p,q.a||0);return{x:p.x+q.x,y:p.y+q.y}})}
function pointIn(p,g){let z=false;for(let i=0,j=g.length-1;i<g.length;j=i++){const a=g[i],b=g[j];if(((a.y>p.y)!==(b.y>p.y))&&(p.x<(b.x-a.x)*(p.y-a.y)/(b.y-a.y)+a.x))z=!z}return z}
function segmentDistance(p,a,b){const dx=b.x-a.x,dy=b.y-a.y,t=Math.max(0,Math.min(1,((p.x-a.x)*dx+(p.y-a.y)*dy)/(dx*dx+dy*dy||1)));return distance(p,{x:a.x+dx*t,y:a.y+dy*t})}
function area(poly){return Math.abs(poly.reduce((s,p,i)=>{const q=poly[(i+1)%poly.length];return s+p.x*q.y-q.x*p.y},0))/2}
function pathLength(g){return g.slice(1).reduce((n,p,i)=>n+distance(g[i],p),0)}
function makePanel(p,k,catalog,group){const t=catalog[k];return{id:id(),kind:'panel',product:k,name:t.name,colour:t.colour,l:t.l,w:t.w,a:0,...p,group}}
function buildRoute(g,k,lanes,catalog){const t=catalog[k];if(!t||!Number.isFinite(lanes)||lanes<1||lanes>4||g.length<2)throw Error('Choose a product and add at least two route points.');const total=g.slice(1).reduce((n,p,i)=>n+Math.ceil(distance(g[i],p)/t.l)*lanes,0);if(total>MAX_ITEMS)throw Error('This route is too large. Split it into smaller sections.');const out=[],group=id(),centres=new Set();for(let i=1;i<g.length;i++){const a=g[i-1],b=g[i],d=distance(a,b);if(d<.05)continue;const angle=Math.atan2(b.y-a.y,b.x-a.x),rows=Math.ceil(d/t.l);for(let n=0;n<rows;n++)for(let lane=0;lane<lanes;lane++){const along=(n+.5)*t.l,offset=(lane-(lanes-1)/2)*t.w,p={x:a.x+Math.cos(angle)*along-Math.sin(angle)*offset,y:a.y+Math.sin(angle)*along+Math.cos(angle)*offset,a:angle};const key=[Math.round(p.x*100),Math.round(p.y*100),Math.round(angle*100)].join(':');if(!centres.has(key)){out.push(makePanel(p,k,catalog,group));centres.add(key)}}}return out}
function intersect(a,b,c,d){const cross=(a,b,c)=>(b.x-a.x)*(c.y-a.y)-(b.y-a.y)*(c.x-a.x);return cross(a,b,c)*cross(a,b,d)<-1e-9&&cross(c,d,a)*cross(c,d,b)<-1e-9}
function selfIntersects(g){for(let i=0;i<g.length;i++)for(let j=i+1;j<g.length;j++){if(j===i+1||i===0&&j===g.length-1)continue;if(intersect(g[i],g[(i+1)%g.length],g[j],g[(j+1)%g.length]))return true}return false}
function buildPad(g,k,catalog,angle){const t=catalog[k];if(g.length<3||area(g)<.01)throw Error('Draw a pad with at least three corners.');if(selfIntersects(g))throw Error('The pad boundary crosses itself. Draw the corners around its outside.');const a=Number.isFinite(angle)?angle:Math.atan2(g[1].y-g[0].y,g[1].x-g[0].x),poly=g.map(p=>rotate(p,-a)),xs=poly.map(p=>p.x),ys=poly.map(p=>p.y),minX=Math.min(...xs),maxX=Math.max(...xs),minY=Math.min(...ys),maxY=Math.max(...ys);if(Math.ceil((maxX-minX)/t.l)*Math.ceil((maxY-minY)/t.w)>MAX_ITEMS)throw Error('This pad is too large. Split it into smaller areas.');const out=[],group=id();for(let y=minY+t.w/2;y<=maxY+t.w/2;y+=t.w)for(let x=minX+t.l/2;x<=maxX+t.l/2;x+=t.l){const rect=[{x:x-t.l/2,y:y-t.w/2},{x:x+t.l/2,y:y-t.w/2},{x:x+t.l/2,y:y+t.w/2},{x:x-t.l/2,y:y+t.w/2}];const valid=rect.every(p=>pointIn(p,poly)||poly.some((q,i)=>segmentDistance(p,q,poly[(i+1)%poly.length])<1e-7));const crossed=rect.some((p,i)=>poly.some((q,j)=>intersect(p,rect[(i+1)%4],q,poly[(j+1)%poly.length])));const intrudes=poly.some(q=>q.x>x-t.l/2+1e-7&&q.x<x+t.l/2-1e-7&&q.y>y-t.w/2+1e-7&&q.y<y+t.w/2-1e-7);if(valid&&!crossed&&!intrudes){const p=rotate({x,y},a);out.push(makePanel({...p,a},k,catalog,group))}}return out}
function snap(items,ids,tolerance){const chosen=items.filter(x=>ids.has(x.id)&&(x.kind==='panel'||x.kind==='accessory')),others=items.filter(x=>!ids.has(x.id)&&(x.kind==='panel'||x.kind==='accessory'));let best;for(const q of chosen){for(const z of others){if(distance(q,z)>Math.max(q.l,q.w)+Math.max(z.l,z.w)+tolerance)continue;if(q.kind==='panel'&&z.kind==='panel'&&q.product!==z.product)continue;const ang=Math.abs(Math.atan2(Math.sin(q.a-z.a),Math.cos(q.a-z.a)));if(ang>.03&&Math.abs(ang-Math.PI)>.03)continue;const p=local(q,z),edges=[];if(Math.abs(q.w-z.w)<.02)edges.push({x:(z.l+q.l)/2,y:0},{x:-(z.l+q.l)/2,y:0});if(Math.abs(q.l-z.l)<.02)edges.push({x:0,y:(z.w+q.w)/2},{x:0,y:-(z.w+q.w)/2});for(const e of edges){const d=distance(p,e);if(d<tolerance&&(!best||d<best.d)){const at=rotate(e,z.a);best={d,dx:z.x+at.x-q.x,dy:z.y+at.y-q.y,parent:z.id,q:q.id}}}}}if(best){items.filter(x=>ids.has(x.id)).forEach(q=>translate(q,best.dx,best.dy));const q=items.find(q=>q.id===best.q);if(q?.kind==='accessory')q.parent=best.parent}return !!best}
function translate(q,dx,dy){if(q.points)q.points=q.points.map(p=>({x:p.x+dx,y:p.y+dy}));else{q.x+=dx;q.y+=dy}}
function bounds(items){let p=[];for(const q of items){if(q.points)p.push(...q.points);else if(q.l&&q.w)p.push(...corners(q));else p.push({x:q.x,y:q.y})}if(!p.length)return null;return{minX:Math.min(...p.map(p=>p.x)),maxX:Math.max(...p.map(p=>p.x)),minY:Math.min(...p.map(p=>p.y)),maxY:Math.max(...p.map(p=>p.y))}}
function schedule(items){const rows=new Map();for(const q of items.filter(q=>['panel','accessory'].includes(q.kind))){const k=q.kind+':'+q.product+':'+q.l+':'+q.w+':'+q.name;const row=rows.get(k)||{name:q.name,product:q.product,kind:q.kind,l:q.l,w:q.w,colour:q.colour,count:0,area:0};row.count++;row.area+=q.l*q.w;rows.set(k,row)}return[...rows.values()]}
function validate(p){if(!p||p.format!=='trakway-studio'||p.version!==2)throw Error('This is not a supported Trakway project.');if(!Array.isArray(p.items)||p.items.length>MAX_ITEMS)throw Error('Project item limit exceeded.');if(!p.background||!['map','image','blank'].includes(p.background.type))throw Error('The project background is invalid.');const finite=x=>typeof x==='number'&&Number.isFinite(x)&&Math.abs(x)<1e8;const point=p=>p&&finite(p.x)&&finite(p.y);if(p.origin&&(!finite(p.origin.lat)||!finite(p.origin.lng)||Math.abs(p.origin.lat)>85||Math.abs(p.origin.lng)>180))throw Error('Project map location is invalid.');if(p.background.type==='map'&&!p.origin)throw Error('Map origin is missing.');if(p.background.type==='image'&&(!/^data:image\/(png|jpeg|webp);base64,/.test(p.background.data||'')||!finite(p.background.mpp)||p.background.mpp<=0||!finite(p.background.width)||!finite(p.background.height)||p.background.width<=0||p.background.height<=0))throw Error('Project image is invalid.');if(p.paper&&(!point(p.paper.a)||!point(p.paper.b)||p.paper.b.x<=p.paper.a.x||p.paper.b.y<=p.paper.a.y||!['landscape','portrait'].includes(p.paper.orientation)))throw Error('Invalid paper frame.');if(p.paths){if(!Array.isArray(p.paths)||p.paths.length>12000)throw Error('Invalid route editing data.');p.paths=p.paths.filter(q=>q&&Array.isArray(q.itemIds)&&q.itemIds.length<=MAX_ITEMS&&Array.isArray(q.points)&&q.points.length<=1000&&q.points.every(point)&&Array.isArray(q.joints)&&q.joints.length<=1000&&q.joints.every(point)&&['route','freeRoute','pad','freePad'].includes(q.mode)&&typeof q.fingerprint==='string'&&q.fingerprint.length<2000000)}const ids=new Set();for(const q of p.items){if(!q.id||ids.has(q.id))throw Error('Duplicate or missing object IDs.');ids.add(q.id);if(!['panel','accessory','text','line','rect','ellipse','measure','symbol'].includes(q.kind))throw Error('Unknown object type.');if(q.points){if(!['line','measure'].includes(q.kind)||q.points.length!==2||!q.points.every(point))throw Error('Invalid line coordinates.')}else{if(['line','measure'].includes(q.kind)||!point(q)||!finite(q.a||0))throw Error('Invalid object coordinates.');if(q.kind!=='text'&&(!finite(q.l)||!finite(q.w)||q.l<=0||q.w<=0))throw Error('Invalid panel or shape dimensions.')}if(q.colour&&!/^#[0-9a-f]{6}$/i.test(q.colour))q.colour='#007b45';if(q.kind==='text')q.text=String(q.text||'').slice(0,120);if(q.name)q.name=String(q.name).slice(0,120)}p.name=String(p.name||'Untitled route plan').slice(0,90);p.notes=String(p.notes||'').slice(0,3000);return p}
function legacy(d){if(!d.imageData||!Array.isArray(d.items)||!Number.isFinite(d.mpp)||d.mpp<=0)throw Error('Legacy project must contain an image with a calibrated scale.');if(!/^data:image\/(png|jpeg|webp);base64,/.test(d.imageData))throw Error('Unsupported legacy image format.');const m=d.mpp,groupMap=new Map();const items=d.items.map((q,i)=>{const p=(q.t==='p'?PRODUCTS:ACCESSORIES)[q.k];if(!p)throw Error('Unknown product in the legacy project.');if(q.group&&!groupMap.has(q.group))groupMap.set(q.group,id());return{id:'legacy-'+i,kind:q.t==='p'?'panel':'accessory',product:q.k,name:p.name,colour:p.colour,l:q.l*m,w:q.w*m,x:q.x*m,y:q.y*m,a:q.a||0,wedge:p.wedge,dir:p.dir,group:groupMap.get(q.group),parent:Number.isInteger(q.parent)?'legacy-'+q.parent:undefined}});for(const a of d.annotations||[]){const colour=/^#[0-9a-f]{6}$/i.test(a.colour)?a.colour:'#ffdb00';if(a.t==='line')items.push({id:id(),kind:'line',points:[a.a,a.b].map(p=>({x:p.x*m,y:p.y*m})),colour,dash:a.dash});else items.push({id:id(),kind:a.t,text:a.text,x:a.x*m,y:a.y*m,a:a.a||0,l:a.w*m,w:a.h*m,colour,alpha:a.alpha,size:a.size||18})}for(const a of d.ms||[])items.push({id:id(),kind:'measure',points:[a.a,a.b].map(p=>({x:p.x*m,y:p.y*m})),colour:'#ffffff'});return{format:'trakway-studio',version:2,id:id(),name:d.projectName||'Imported route plan',site:'',ref:'',notes:'Imported from Trakway Route Designer '+(d.version||'v1'),origin:null,background:{type:'image',data:d.imageData,mpp:m,width:1,height:1,calibrated:true},items}}
const api={R,DEG,MAX_ITEMS,PRODUCTS,ACCESSORIES,id,distance,project,unproject,toLocal,toLatLng,rotate,local,corners,pointIn,segmentDistance,area,pathLength,buildRoute,buildPad,snap,translate,bounds,schedule,validate,legacy};root.TrakwayCore=api;if(typeof module!=='undefined')module.exports=api;
})(typeof window==='undefined'?globalThis:window);
